# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ewayn <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/16 09:22:43 by ewayn             #+#    #+#              #
#    Updated: 2021/02/16 10:28:25 by ewayn            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= ft_display_file

SRCS	= main.c

OBG		= *.o

RM		= rm -f

CMPL	= cc -Wall -Wextra -Werror

all:
		${CMPL} ${SRCS} -o ${NAME}

clean:
		${RM} ${OBG}

fclean: clean
		${RM} ${NAME}

re: fcelan re
